name: Autobuild and Test

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest
    
        steps:
          - name: Setup Conda
            env: 
              ALANA_KEY: ${{ secrets.alana_key }}
            run: |
              # from https://stackoverflow.com/questions/28852841/install-anaconda-on-ubuntu-or-linux-via-command-line
              cd ~
              # You can change what anaconda version you want at 
              # https://repo.continuum.io/archive/
              wget https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh
              bash Miniconda3-4.7.12.1-Linux-x86_64.sh -b -p ~/anaconda
              rm Miniconda3-4.7.12.1-Linux-x86_64.sh
              echo 'export PATH="~/anaconda/bin:$PATH"' >> ~/.bashrc
              # Refresh basically
              source .bashrc
              conda update conda
              cd $OLDPWD
          - name: Checkout Code
            uses: actions/checkout@v2
          - name: Setup Environment
            run: |
              # Use deploy key
              eval $(ssh-agent)
              ssh-add $ALANA_KEY
              ssh-keyscan -H github.com >> /etc/ssh/ssh_known_hosts
              # ... so it can be picked up in autosetup
              bash setup_environment.sh
              cd $GITHUB_WORKSPACE
          - name: Lint with flake8
            run: |
              # stop the build if there are Python syntax errors or undefined names
              flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude alana_utils
              # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
              flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude alana_utils
          - name: Test with pytest
            run: |
              pytest
