version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_ADMIN_PORT}:15672"
    expose:
      - ${RABBITMQ_PORT}
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "${RABBITMQ_PORT}"]
      interval: 5s
      timeout: 15s
      retries: 1

  # --------------------------------- Services --------------------------------- #
  automatic_speech_recognition:
    container_name: automatic_speech_recognition
    image: ayesaac:latest
    restart: always
    depends_on:
      - rabbitmq
    env_file: .env
    command:
      - python
      - -u
      - -m
      - ayesaac.services.automatic_speech_recognition
    volumes:
      - type: bind
        source: ./ayesaac/services/automatic_speech_recognition
        target: /app/ayesaac/services/automatic_speech_recognition

  camera_manager:
    container_name: camera_manager
    image: ayesaac:latest
    restart: always
    depends_on:
      - rabbitmq
    env_file: .env
    command:
      - python
      - -u
      - -m
      - ayesaac.services.camera_manager.main
    volumes:
      - type: bind
        source: ./ayesaac/services/camera_manager
        target: /app/ayesaac/services/camera_manager

  colour_detection:
    container_name: colour_detection
    image: ayesaac:latest
    restart: always
    depends_on:
      - rabbitmq
    env_file: .env
    command:
      - python
      - -u
      - -m
      - ayesaac.services.colour_detection.main
    volumes:
      - type: bind
        source: ./ayesaac/services/colour_detection
        target: /app/ayesaac/services/colour_detection

  external_interface:
    container_name: external_interface
    image: ayesaac:latest
    restart: always
    depends_on:
      - rabbitmq
    env_file: .env
    command:
      - python
      - -u
      - -m
      - ayesaac.services.external_interface
    volumes:
      - type: bind
        source: ./ayesaac/services/external_interface
        target: /app/ayesaac/services/external_interface

  interpreter:
    container_name: interpreter
    image: ayesaac:latest
    restart: always
    depends_on:
      - rabbitmq
    env_file: .env
    command:
      - python
      - -u
      - -m
      - ayesaac.services.interpreter.main
    volumes:
      - type: bind
        source: ./ayesaac/services/interpreter
        target: /app/ayesaac/services/interpreter

  manager:
    container_name: manager
    image: ayesaac:latest
    restart: always
    depends_on:
      - rabbitmq
    env_file: .env
    command:
      - python
      - -u
      - -m
      - ayesaac.services.manager.main
    volumes:
      - type: bind
        source: ./ayesaac/services/manager
        target: /app/ayesaac/services/manager

  natural_language_generator:
    container_name: natural_language_generator
    image: ayesaac:latest
    restart: always
    depends_on:
      - rabbitmq
    env_file: .env
    command:
      - python
      - -u
      - -m
      - ayesaac.services.natural_language_generator.main
    volumes:
      - type: bind
        source: ./ayesaac/services/natural_language_generator
        target: /app/ayesaac/services/natural_language_generator

  natural_language_understanding:
    container_name: natural_language_understanding
    image: ayesaac:latest
    restart: always
    depends_on:
      - rabbitmq
    env_file: .env
    command:
      - python
      - -u
      - -m
      - ayesaac.services.natural_language_understanding.main
    volumes:
      - type: bind
        source: ./ayesaac/services/natural_language_understanding
        target: /app/ayesaac/services/natural_language_understanding

  object_detection:
    container_name: object_detection
    image: ayesaac:latest
    restart: always
    depends_on:
      - rabbitmq
    env_file: .env
    command:
      - python
      - -u
      - -m
      - ayesaac.services.object_detection.main
    volumes:
      - type: bind
        source: ./ayesaac/services/object_detection
        target: /app/ayesaac/services/object_detection

  optical_character_recognition:
    container_name: optical_character_recognition
    image: ayesaac:latest
    restart: always
    depends_on:
      - rabbitmq
    env_file: .env
    command:
      - python
      - -u
      - -m
      - ayesaac.services.optical_character_recognition.main
    volumes:
      - type: bind
        source: ./ayesaac/services/optical_character_recognition
        target: /app/ayesaac/services/optical_character_recognition

  position_detection:
    container_name: position_detection
    image: ayesaac:latest
    restart: always
    depends_on:
      - rabbitmq
    env_file: .env
    command:
      - python
      - -u
      - -m
      - ayesaac.services.position_detection.main
    volumes:
      - type: bind
        source: ./ayesaac/services/position_detection
        target: /app/ayesaac/services/position_detection

  web:
    container_name: web
    image: ayesaac:latest
    restart: always
    depends_on:
      - rabbitmq
    env_file: .env
    environment:
      FLASK_APP: "./ayesaac/services/web/app.py"
    ports:
      - "${ENDPOINT_PORT}:5000"
    command:
      - flask
      - run
      - "--host=0.0.0.0"
    volumes:
      - type: bind
        source: ./ayesaac/services/web
        target: /app/ayesaac/services/web
