version: '3'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=test-user
      - RABBITMQ_DEFAULT_PASS=test-user
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  ayesaac:
    container_name: ayesac_app
    restart: always
    depends_on:
      - rabbitmq
    volumes:
      - ./ayesaac/services_log:/aye-saac/ayesaac/services_log
    ports:
      - "5000:5000"
    build:
      context: .
    environment:
      - NONLOCAL_RABBITMQ=true
#    environment:
#      - RABBITMQ_DEFAULT_USER=test-user
#      - RABBITMQ_DEFAULT_PASS=test-user