# This data objects lists the classes that can be considered "anchors", i.e. they
# might be useful for positioning items of interest. The relationships list likely
# positioning to be found, e.g. an item is found "on" a table
ANCHORS = {
    "fridge": {"name": "fridge", "relationships": ["in", "on", "next to"]},
    "refrigerator": {"name": "refrigerator", "relationships": ["in", "on", "next to"]},
    "cupboard": {"name": "cupboard", "relationships": ["in", "on", "next to"]},
    "bin": {"name": "bin", "relationships": ["in", "on", "next to"]},
    "sink": {"name": "sink", "relationships": ["in", "next to"]},
    "door": {"name": "door", "relationships": ["in", "next to"]},
    "kettle": {"name": "kettle", "relationships": ["next to"]},
    "hob": {"name": "hob", "relationships": ["on", "next to"]},
    "dishwasher": {"name": "dishwasher", "relationships": ["in", "on", "next to"]},
    "table": {"name": "table", "relationships": ["on", "next to"]},
    "microwave": {"name": "microwave", "relationships": ["in", "on", "next to"]},
    "oven": {"name": "oven", "relationships": ["in", "on", "next to"]},
    "cooker:slow": {"name": "cooker:slow", "relationships": ["in", "on", "next to"]},
    "rack:drying": {"name": "rack:drying", "relationships": ["in", "on", "next to"]},
    "top": {"name": "top", "relationships": ["on", "next to"]},
    "machine:washing": {"name": "machine:washing", "relationships": ["in", "on", "next to"]},
    "freezer": {"name": "freezer", "relationships": ["in", "on", "next to"]},
    "maker:coffee": {"name": "maker:coffee", "relationships": ["on", "next to"]},
    "floor": {"name": "floor", "relationships": ["on"]},
    "processor:food": {"name": "processor:food", "relationships": ["in", "on", "next to"]},
    "shelf": {"name": "shelf", "relationships": ["on", "next to"]},
    "fan:extractor": {"name": "fan:extractor", "relationships": ["below", "on", "next to"]},
    "toaster": {"name": "toaster", "relationships": ["in", "on", "next to"]},
    "chair": {"name": "chair", "relationships": ["on", "next to"]},
    "desk": {"name": "desk", "relationships": ["on", "next to"]},
    "drawer": {"name": "drawer", "relationships": ["in"]},
    "blender": {"name": "blender", "relationships": ["in", "on", "next to"]},
    "window": {"name": "window", "relationships": ["on", "next to"]},
    "stereo": {"name": "stereo", "relationships": ["on", "next to"]},
    "wall": {"name": "wall", "relationships": ["on", "next to"]},
    "lamp": {"name": "lamp", "relationships": ["next to"]},
    "couch": {"name": "couch", "relationships": ["on", "next to"]},
    "dining table": {"name": "dining table", "relationships": ["on", "next to"]},
    "tv": {"name": "tv", "relationships": ["on", "next to"]},
}