name: Docker CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submobules
      uses: actions/checkout@v2
      with: 
        repository: Hangsii/secret_alana_utils
        token: ${{secrets.ALANA_PAT}}
        path: secret_alana_utils
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.14
      with:
        name: Aye-saac/docker/server
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com

